---
title: "BLAST output from NCBI"
output: html_document
date: "2024-10-14"
---

Load libraries

```{r}
library(ggplot2) ## for plotting
library(dplyr) ## for data table manipulation
library(tidyr) ## for data table manipulation
library(readr) ## for reading in tsv files
library(readxl) ## for reading in excel files
library(stringr) ## for data transformation
library(strex) ## for data transformation
library(writexl) ## for excel output
library(purrr) ## for data transformation
library(funrar) ## for make_relative()
library(tidyverse) ## for data table manipulation
```

Metadata 

```{r}
meta <- read.csv("data/metadata/samplesheet.csv") %>% dplyr::select(sampleID) 
```

BLAST output

```{r}
NCBI_taxassigned <- read.delim2("data/results/NCBI_taxassigned.txt", header=F, 
                                col.names = c("staxid", "Phylo")) %>%
  
  ## creating taxonomic assignment columns
  separate(Phylo, c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species_name"), sep = ";") %>%
  
  ## creating species column based on Species_name
  mutate(., species = str_after_nth(Species_name, " ", 1))

Blast_NCBI <- read.table("data/results/BLASTResults_NCBI.txt", header=F,
                           col.names = c("ASV_ID", "sseqid", "sscinames", "staxid", "pident", "length", "mismatch",
                                         "gapopen", "qstart", "qend", "sstart", "send", "evalue", "bitscore"),
                           colClasses = c(rep("character", 3), "integer", rep("numeric", 9))) %>%
  left_join(., NCBI_taxassigned, by = "staxid") 

## Exporting choices
Blast_NCBI %>% 
  mutate(Choice = "") %>%
  
  ## cutting to top choice 
  group_by(ASV_ID) %>%
  slice_max(pident, n=1) %>%
  
  ## combining the species name
  dplyr::select(ASV_ID, Species_name, Choice) %>% distinct() %>%
  mutate(Species_name = paste0(Species_name, collapse = ";")) %>% distinct() %>%
  filter(grepl(";", Species_name)) %>%
  mutate(Species_name = gsub("uncultured ", "", Species_name)) %>%
  write_xlsx("data/results/Blast_choices.xlsx")


## Genus level
Blast_NCBI %>% 
  mutate(Choice = "") %>%
  
  ## cutting to top choice 
  group_by(ASV_ID) %>%
  slice_max(pident, n=1) %>%
  slice_max(length, n=1) %>%
  
  ## combining the species name
  dplyr::select(ASV_ID, Genus, Choice) %>% distinct() %>%
  mutate(Genus = paste0(Genus, collapse = ";")) %>% distinct() %>%
  filter(grepl(";", Genus)) %>% 
  write_xlsx("data/results/Blast_choices_genus.xlsx")
```

Load ASV table

```{r}
ASV_table <- read_tsv("data/results/dada2/ASV_table.tsv", show_col_types = FALSE) %>%
  ## calculate the sum of all reads for each ASV
  mutate(., ASV_sum = rowSums(across(where(is.numeric)))) %>% 

  ## calculate a ranking based on those sum calculated above
  mutate(ASV_rank = rank(-ASV_sum, ties.method='random')) %>%

  ## move the sum and rank columns to after ASV_ID and arrange by rank
  relocate(c(ASV_sum,ASV_rank), .after = ASV_ID) %>% arrange((ASV_rank))

## creating list of rankings
ASV_rank_list <- ASV_table %>% dplyr::select(ASV_ID, ASV_sum, ASV_rank)
```

Picking between multiple hits 

```{r}
multiple_hit_choice_edited <- read_xlsx("data/results/Blast_choices_genus_edited.xlsx") %>%
  ## selecting only columns needed 
  dplyr::select(ASV_ID, Choice) 

Blast_NCBI_edited <- Blast_NCBI %>% dplyr::select(ASV_ID, Genus, pident, length) %>% distinct() %>% ungroup()

# Loop through each row of the dataframe
for (i in multiple_hit_choice_edited$ASV_ID) {
  # Extract the current row (will do this for each ASV_ID in the choice df)
  current_row <- multiple_hit_choice_edited %>% subset(ASV_ID==i)

  # Apply filter based on the current row's condition
  Blast_NCBI_edited <- Blast_NCBI_edited %>%
    filter(case_when(ASV_ID == current_row$ASV_ID ~ Genus == current_row$Choice,
           TRUE ~ TRUE))
}

### Check the below output to confirm the filtering steps above worked (if it worked, it won't be in output)
Blast_NCBI_edited %>% group_by(ASV_ID) %>% slice_max(pident, n=1) %>% slice_max(length, n=1) %>%
  count() %>% filter(n>1)
```

```{r}
## 3,558 unique ASVs 
Blast_df_annotated <- Blast_NCBI_edited %>% group_by(ASV_ID) %>%
  slice_max(pident, n=1) %>% slice_max(length, n=1) %>% dplyr::select(-pident, -length) %>% ungroup()

length(unique(Blast_df_annotated$Genus))

Blast_df_annotated <- Blast_df_annotated %>% left_join(
  Blast_NCBI %>% group_by(ASV_ID) %>%
    slice_max(pident, n=1) %>% slice_max(length, n=1) %>%
    dplyr::select(ASV_ID, Kingdom, Phylum, Class, Order, Family, Genus) %>% distinct(),
  by = join_by(ASV_ID, Genus)) %>% 
  mutate(across(where(is.character), 
                ~ifelse(. == "unassigned" | . == "Unassigned", NA, .))) %>%
  group_by(ASV_ID) %>%
  filter(case_when(n() >= 2 ~ !is.na(Phylum), TRUE ~ TRUE)) %>%
  filter(case_when(n() >= 2 ~ !is.na(Class), TRUE ~ TRUE)) %>%
  filter(case_when(n() >= 2 ~ !is.na(Order), TRUE ~ TRUE)) %>%
  filter(case_when(n() >= 2 ~ !is.na(Family), TRUE ~ TRUE)) %>%
  
  ## multiple unassigned genera 
  filter(case_when(
    ASV_ID == "6495422bf9bb691849ecdf54ca51879b" ~ Family == "Planctomycetaceae",
    ASV_ID == "aea1a80e8d8f19fe338428911a2452d8" ~ Family == "Vicinamibacteraceae",
    ASV_ID == "77996a87b6796c3f82d484dd9ceed013" ~ Family == "Selenomonadaceae",
    ASV_ID == "f03f14acacb94fdc8c29b6b68e974ff8" ~ Family == "Planctomycetaceae",
           TRUE ~ TRUE)) %>%
  
  mutate(across(where(is.character), 
                ~ifelse(is.na(.), "Unassigned", .)))
  
  
Blast_df_annotated %>% group_by(ASV_ID) %>% 
  count() %>% filter(n>1)

nrow(Blast_df_annotated) == length(unique(Blast_df_annotated$ASV_ID))
```

```{r}
df <- ASV_table %>% left_join(., Blast_df_annotated, by = "ASV_ID") %>%
    mutate(across(where(is.character), 
                ~ifelse(is.na(.), "Unassigned", .)))

df %>% write_xlsx("data/results/Results.xlsx")
```






